Repository hms-dbmi/pic-sure-bdc-frontend, pull requests merged in 2023-09, with the labels that each got.

#230 [ALS-5010] Allow Authorized access for users with only open datasets
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/session.js
Labels: bug

#229 [ALS-4943] Remove temp "other" category Stat Vis fix
  biodatacatalyst-ui/src/main/webapp/picsureui/openPicsure/outputPanel.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/tool-suite-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/visualization-modal-view.js
Labels: ignore-for-release

#232 ALS-5036: Fix search case bug
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/categorical-filter-modal-view.js
Labels: bug

#234 Add named datasets
  biodatacatalyst-ui/src/main/webapp/picsureui/api-interface/apiPanel.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/api-interface/apiPanelView.js
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/dataset/dataset-manage.js
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/dataset/dataset-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/header.js
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/external-export-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/package-view.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/package-view.js
  biodatacatalyst-ui/src/main/webapp/psamaui/user/userToken.hbs
  biodatacatalyst-ui/src/main/webapp/psamaui/user/userToken.js
Labels: enhancement

#233 [ALS-4918] Updates to styles to support core styles
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css
Labels: ignore-for-release

#236 [ALS-5107] Add configurable banner section
  biodatacatalyst-ui/src/main/resources/banner_config.json
Labels: ignore-for-release
