Repository hms-dbmi/pic-sure-bdc-frontend, pull requests merged in 2023-10, with the labels that each got.

#237 Fix API token render
  biodatacatalyst-ui/src/main/webapp/picsureui/api-interface/apiPanelView.js
Labels: bug

#240 Release 0004
  biodatacatalyst-ui/Dockerfile
  biodatacatalyst-ui/src/main/resources/banner_config.json
  biodatacatalyst-ui/src/main/webapp/picsureui/api-interface/apiPanelView.js
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/router.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/tool-suite-view.js
Labels: ignore-for-release

#241 [ALS-4919] "Something went wrong" page
  biodatacatalyst-ui/Dockerfile
Labels: ignore-for-release

#243 [ALS-5105][ALS5106] Alter to use bdc blue for dataset
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css
Labels: enhancement

#242 [ALS-5144] Add documentation to file
  biodatacatalyst-ui/Dockerfile
Labels: documentation
