Repository hms-dbmi/pic-sure-bdc-frontend, pull requests merged in 2023-12, with the labels that each got.

#257 [ALS-5208] Remove Open Access from Authorized BDC
  biodatacatalyst-ui/src/main/webapp/picsureui/header/header.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/router.js
  biodatacatalyst-ui/src/main/webapp/picsureui/studyAccess/study-utility.js
  biodatacatalyst-ui/src/main/webapp/picsureui/studyAccess/studyAccess.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/studyAccess/studyAccess.js
Labels: enhancement

#258 [ALS-5439] Add Open Access header
  biodatacatalyst-ui/src/main/webapp/picsureui/header/header.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/header.js
Labels: enhancement

#260 [ALS-5379] Fix actions and variable info modal bugs
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/filter-model.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-view.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-template.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-view.js
Labels: bug

#261 [ALS-2794] Avoid using FHS for Auth Access Product Walkthrough
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-view.js
Labels: enhancement

#262 Release/0006
  biodatacatalyst-ui/src/main/webapp/picsureui/header/header.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/landing/landing.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/landing/landing.js
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/header.js
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/router.js
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/data-hierarchy-view-list.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/data-hierarchy-view.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/data-hierarchy-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/filter-model.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-view.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-util.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-template.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/studyAccess/study-utility.js
  biodatacatalyst-ui/src/main/webapp/picsureui/studyAccess/studyAccess.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/studyAccess/studyAccess.js
Labels: ignore-for-release

#263 [ALS-5456] Implement lazy load for Plotly in visualization-modal-view
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/visualization-modal-view.js
Labels: enhancement

#265 [ALS-5534] Render template earlier in landing.js
  biodatacatalyst-ui/src/main/webapp/picsureui/landing/landing.js
Labels: bug

#266 Release/0007
  biodatacatalyst-ui/src/main/webapp/picsureui/landing/landing.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/visualization-modal-view.js
Labels: ignore-for-release
