Repository hms-dbmi/pic-sure-bdc-frontend, pull requests merged in 2023-11, with the labels that each got.

#244 [ALS-4773] Update to dataset view overrides
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/dataset/dataset-view.js
Labels: enhancement

#247 [ALS-5337] Add return all option
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/categorical-filter-modal-view.js
Labels: enhancement

#245 [ALS-5287] Remove Withdrawn Studies Button
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css
  biodatacatalyst-ui/src/main/webapp/picsureui/studyAccess/studyAccess.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/studyAccess/studyAccess.js
Labels: enhancement

#246 [ALS-5186] Add legend to Stat Vis for Obfuscated region
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/visualization-modal-view.js
Labels: enhancement

#248 [ALS-5289] Hide request button when study is suspended
  biodatacatalyst-ui/src/main/webapp/picsureui/studyAccess/studyAccess.js
Labels: enhancement

#251 [ALS-5128] Hide accession when there no consent code
  biodatacatalyst-ui/src/main/webapp/picsureui/studyAccess/studyAccess.js
Labels: bug

#250 [ALS-5229] Create informative Login page for Auth PIC-SURE
  biodatacatalyst-ui/Dockerfile
  biodatacatalyst-ui/login_dots.png
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/package-view.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/seven-bridges-export-view.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/terra-export-view.hbs
  biodatacatalyst-ui/src/main/webapp/psamaui/login/fence_login.hbs
Labels: enhancement

#252 [ALS-5229] Incorporate-icons-and-search-bar-on-Open-PIC-SURE-landing-page
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-view.js
Labels: enhancement, ignore-for-release
