Repository hms-dbmi/pic-sure-bdc-frontend, pull requests merged in 2024-03, with the labels that each got.

#286 [ALS-6058] Refactor search term selection in search view
  biodatacatalyst-ui/src/main/webapp/picsureui/openPicsure/studiesModal.js
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/router.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-view.js
Labels: enhancement

#285 [ALS-5548] Stigmatizing Variables Displayed in Dataset View of Open PIC-SURE
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/datatable-filter-modal-view.js
Labels: bug

#288 Merge for AIM-AHEAD 2024-03-14-Release
  biodatacatalyst-ui/src/main/webapp/picsureui/landing/landing.js
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/router.js
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/search.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/datatable-filter-modal-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/filter-list-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/package-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-view.js
Labels: ignore-for-release

#289 [ALS-6144] Fix filter variable info modal button
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-view.js
Labels: bug

#292 2024-03-28-Release
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/datatable-filter-modal-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/filter-model.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-view.js
Labels: ignore-for-release

#294 [ALS-6186] Filter name word break
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/filter-list-view.hbs
Labels: bug

#296 [ALS-6165] Disable directory browsing
  biodatacatalyst-ui/Dockerfile
Labels: enhancement
