Repository hms-dbmi/pic-sure-bdc-frontend, pull requests merged in 2024-04, with the labels that each got.

#297 [ALS-6223] Duplicate graphs on BDC StatViz
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/visualization-modal-view.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/visualization-modal-view.js
Labels: bug

#299 [ALS-6232] Update Login buttons
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css
  biodatacatalyst-ui/src/main/webapp/psamaui/login/fence_login.hbs
Labels: enhancement

#300 [ALS-6227] Contact Us link opens in a new tab
  biodatacatalyst-ui/src/main/webapp/picsureui/header/header.hbs
Labels: bug

#298 [ALS-6171] Show Stigmatizing variables in open access but disable filtering on them
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/datatable-filter-modal-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/no-results-open-help-view.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-template.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-view.js
Labels: enhancement

#302 2024-04-11-release
  biodatacatalyst-ui/Dockerfile
  biodatacatalyst-ui/src/main/webapp/picsureui/header/header.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/datatable-filter-modal-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/no-results-open-help-view.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-template.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/visualization-modal-view.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/visualization-modal-view.js
  biodatacatalyst-ui/src/main/webapp/psamaui/login/fence_login.hbs
Labels: ignore-for-release

#303 [ALS-6171] Fix bug disabling filter button on info modal
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-template.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-view.js
Labels: ignore-for-release
