Repository hms-dbmi/pic-sure-bdc-frontend, pull requests merged in 2024-02, with the labels that each got.

#273 [ALS-5583] Update build process to support AIM-AHEAD PIC-SURE
  biodatacatalyst-ui/Dockerfile
  biodatacatalyst-ui/overrride.Dockerfile
  biodatacatalyst-ui/src/main/webapp/picsureui/header/header.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/userDetails.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-view.hbs
Labels: enhancement

#278 [ALS-5703] AIM-AHEAD PIC-SURE Help Tab
  biodatacatalyst-ui/src/main/webapp/picsureui/common/pic-dropdown.js
Labels: bug, enhancement

#279 [ALS-5789] Add loading screen while loading variable modal
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-view.js
Labels: enhancement

#281 [ALS-5584] Add ontology instance dependency to search-view
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-view.js
Labels: bug, ignore-for-release

#283 [ALS-5077] BDC: Obfuscation in Participant Counts by Study
  biodatacatalyst-ui/src/main/webapp/picsureui/openPicsure/studiesModal.js
Labels: enhancement
