Repository hms-dbmi/pic-sure-bdc-frontend, pull requests merged in 2024-01, with the labels that each got.

#267 [ALS-5510] Update JUnit
  biodatacatalyst-ui/pom.xml
Labels: dependencies, ignore-for-release

#268 [ALS-5567] Replace hard-coded URLs with variables in not_authorized.hbs
  biodatacatalyst-ui/src/main/webapp/psamaui/login/not_authorized.hbs
Labels: enhancement

#269 [ALS-5669] Update Seven bridges text and link
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/seven-bridges-export-view.hbs
Labels: enhancement

#270 [ALS-5474] Fix bug where study tags were showing in the variable tags list
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/tag-filter-view.js
Labels: bug

#272 [ALS-5336] Fix bug where users were seeing the DCC study tag when they should not
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-util.js
Labels: bug

#275 [ALS-5589] Data Dashboard: align to header
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css
Labels: bug

#274 [ALS-1302] Update text to Freeze9
  biodatacatalyst-ui/src/main/webapp/picsureui/studyAccess/studyAccess.js
Labels: ignore-for-release

#276 Merge release/0008 to prepare for Open and Authorized BioData Catalyst release
  biodatacatalyst-ui/Dockerfile
  biodatacatalyst-ui/httpd-vhosts-dev.conf
  biodatacatalyst-ui/httpd-vhosts.conf
  biodatacatalyst-ui/pom.xml
  biodatacatalyst-ui/src/main/webapp/picsureui/common/terms-of-use.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/common/terms-of-use.js
  biodatacatalyst-ui/src/main/webapp/picsureui/header/header.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/header.js
  biodatacatalyst-ui/src/main/webapp/picsureui/overrides/styles.css
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-util.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/seven-bridges-export-view.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/tag-filter-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/studyAccess/studyAccess.js
  biodatacatalyst-ui/src/main/webapp/psamaui/login/not_authorized.hbs
Labels: enhancement
