Repository hms-dbmi/pic-sure-bdc-frontend, pull requests merged in 2024-05, with the labels that each got.

#306 ALS-6375: Suppress showing user 0 results in open-pic-sure
  biodatacatalyst-ui/src/main/webapp/picsureui/openPicsure/studiesModal.js
  biodatacatalyst-ui/src/main/webapp/picsureui/openPicsure/studiesModalView.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/tool-suite-view.js
Labels: enhancement

#304 [ALS-6308] User feedback on Stigmatizing Variables
  biodatacatalyst-ui/src/main/webapp/picsureui/openPicsure/studiesModalView.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/no-results-open-help-view.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/open-picsure-tag-help-view.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-template.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-view.js
Labels: enhancement

#310 Release
  biodatacatalyst-ui/src/main/webapp/picsureui/openPicsure/studiesModalView.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/datatable-filter-modal-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/no-results-open-help-view.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/open-picsure-tag-help-view.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/search-results-view.js
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-template.hbs
  biodatacatalyst-ui/src/main/webapp/picsureui/search-interface/variable-info-modal-view.js
Labels: ignore-for-release

#311 [ALS-6403] Fix open study counts ordering in modal
  biodatacatalyst-ui/src/main/webapp/picsureui/openPicsure/studiesModal.js
Labels: bug
